### ISSUE TITLE
Change colors and font type to Rubik

### ISSUE THREAD

**Issue by annatesla** [poap-xyz/poap-qr-kiosk#47]
## Problem/Oppurtunity
Change UI to conform to current POAP branding style

## Context
- https://qr.poap.tech/#/
- https://qr.poap.tech/#/create

## Checklist
**https://qr.poap.tech/#/** (image 1)

- [ ] Title: Rubik / Semibold. Color: HEX #7C72E2
- [ ] Sub-headers: Rubik / Regular. Colour: HEX #F59DB6
- [ ] Text: Rubik / Regular. Color: HEX #3A3A3A

**https://qr.poap.tech/#/create** 

- [ ] Text: Rubik / Regular. Color: HEX #3A3A3A

## Image reference 
![2022-08-08 14_51_49-QR dispenser – Figma](https://user-images.githubusercontent.com/10008331/183422336-57d9b946-6221-46c4-b810-c0031ccf157f.png)

## Links
Ask @annatesla
