### ISSUE TITLE
Farmer resistant gamification

### ISSUE THREAD

**Issue by actuallymentor** [poap-xyz/poap-qr-kiosk#8]
Goal: farmer-resistant links by default, enable playing a game (pacman, snake, flappy bird) as proof of human work.

## Phase 1: scalable expiring links

- [ ] `event` gets property `public_auth` with `{ expires: Number, token: uuidv4() }`
- [ ] QR in interface listens to `event` renders `claim/{eventId}/{token}`
- [ ] Cloud function checks `/publicEventMeta/{eventId}/public_auth.expires` and generates new one if `expires < Date.now()`
- [ ] On call, `claim/{eventId}/{token}`:
  - [ ] Checks if the `token` is the current one for the event
  - [ ] Generated `/challenges` document with `eventid, token, expires` where `expires` is a reasonable delay for a human
  - [ ] Respond with redirect to `/#/claim/{eventid}/{token}`
    - [ ] `/#/claim` verifies captcha humanity
    - [ ] `/#/claim` calls `get_code( eventid, token )`
      - [ ] `get_code` verifies app check and that the eventid, token, and expires are still valid. Returns a valid code.
      - [ ] `/#/claim` redirects to `app.poap.xyz/claim/{claimcode}`
- [ ] Disable unused permissions

## Phase 2: enable proof of human work

- [ ] `/#/claim/{eventid}/{token}` has a 'Prove your humanity by playing a game' screen with a 'Start Game' button
  - [ ] Instruct that 1 level must be finished or X score must be reached, timeout redirects to `/#/failed/`
  - [ ] Start Game must be pressed within X seconds of page loading (prevent multi-tabbers)
 - [ ] Button starts game
   - [ ] If game fails, redirect to `/#/failed/`
 - [ ] Once game is played for Y seconds, show `Claim POAP` button
   - [ ] Button is visible for Z seconds
   - [ ] Redirect to `/#/fail` on timeout
